### PR TITLE
Fixes #32 Add used redis channel to incoming events

### LINKED ISSUE #32: Add pattern_channel channel name matching
I'd really like to see if we can incorporate the channel name for the redis pattern_channel data type.  It looks like right now the channel is just being thrown away in the response when receiving messages under the pattern channel listener.  This would be pretty easy to do if we can just add the name of the channel to the queue event propogated [here](https://github.com/logstash-plugins/logstash-input-redis/blob/master/lib/logstash/inputs/redis.rb#L332).

Any thoughts on this?  I know redis is widely used broker for logstash messages, so i'm not sure what type of performance impact this would have, but it would make generic channel subscriptions and then attaching particular channel names in the forwarded output much simpler.

### PR DESCRIPTION
**Pull request by joac**
Adds the redis channel used to events, useful for selecting filters and add dynamic data to events

### CODE REVIEW

**Comment by joac** [comment]
@suyograo Let me know if is necessary to add a setting to enable/disable this feature

**Comment by guyboertje** [comment]
@joac - I think this is fine as is.

LGTM

**Comment by DavidFlamini** [comment]
Hi guys, do you have a timeline for merging this PR? Thanks!

**Comment by jsvd** [comment]
merged in https://github.com/logstash-plugins/logstash-input-redis/commit/809495173b57f2864f9d19b027a9cb7a76a7aac4

**Pull request closed without merging**
