### PR TITLE
Fix typo in module name

### LINKED ISSUE #15: v1.0.1 "Couldn't find any input plugin named 'redis'"
logstash 1.5.3. When version up input-redis from 1.0.0 to 1.0.1, error occured.

{:timestamp=>"2015-07-27T09:03:31.372000+0900", :message=>"The error reported is: \n  Couldn't find any input plugin named 'redis'. Are you sure this is correct? Trying to load the redis input plugin resulted in this error: NameError"}

Maybe the cause is...

+module Logstash module Inputs class Redis < LogStash::Inputs::Threadable
+# class LogStash::Inputs::Redis < LogStash::Inputs::Threadable

### PR DESCRIPTION
**Pull request by shaharmor**
Fixes #15 
Duplicate of #16 (Opened due to urgency)

### CODE REVIEW

**Comment by shaharmor** [comment]
@suyograo any chance of merging this and publishing new version? Obviously this is a critical bug.

**Comment by nxhack** [comment]
@shaharmor Thank you.

**Comment by suyograo** [comment]
@shaharmor thanks! 1.0.2 has been published

**Comment by shaharmor** [comment]
@suyograo thank you very much! i've added another PR (#20) with the changelog updated to reflect the change

**Comment by suyograo** [comment]
Done. Apologies hitting this :(

**Pull request closed without merging**
